branches:
- spec: master
- spec: pr-1
  call: default
tools:
  jdk:
    - 8

flows:
  default:
    - echo "Hello Looper!"
    - java -version
    - echo "JAVA_HOME=$JAVA_HOME"
    - |
      FILES=$(ls -l /tmp)
      echo $FILES
      
  pr:
    - call: default

